services:
  vpn:
    container_name: vpn
    image: vm75/openvpn-proxy:latest
    cap_add:
      - NET_ADMIN
    environment:
      - KILL_SWITCH=on
      - SOCKS_PROXY=on
      - HTTP_PROXY=on
      - SUBNETS=192.168.1.0/24,10.89.0.0/16
    dns:
      - 1.1.1.1
      - 1.0.0.1
    devices:
      - /dev/net/tun
    ports:
      - 8081:8081 # config-server
      - 8080:8080 # http-proxy
      - 1080:1080 # socks-proxy
      - 8112:8112 # deluge
      - 8221:8221 # storm
      - 9117:9117 # jackett
    volumes:
      - ./volumes/openvpn-proxy:/data
    restart: unless-stopped
