FROM alpine AS build-sockd

ARG DANTE_VERSION=1.4.3

RUN apk add --no-cache build-base && \
    wget https://www.inet.no/dante/files/dante-$DANTE_VERSION.tar.gz --output-document - | tar -xz && \
    cd dante-$DANTE_VERSION && \
    ac_cv_func_sched_setscheduler=no ./configure --disable-client && \
    make install

RUN cp /usr/local/sbin/sockd /build/sockd
